### ISSUE TITLE
Windows Terminal theme

### ISSUE THREAD

**Issue by richeney** [marlosirapuan/vscode-theme-nord-deep#1]
Great theme. (And I love your Rocky profile pic!)

If you use Windows Terminal then here is the matching object for the schemes list:

```json
{
    "background": "#232731",
    "black": "#3b4252",
    "blue": "#81a1c1",
    "brightBlack": "#4c566a",
    "brightBlue": "#81a1c1",
    "brightCyan": "#8fbcbb",
    "brightGreen": "#a3be8c",
    "brightPurple": "#b48ead",
    "brightRed": "#bf616a",
    "brightWhite": "#eceff4",
    "brightYellow": "#ebcb8b",
    "cyan": "#88c0d0",
    "foreground": "#d8dee9",
    "green": "#a3be8c",
    "name": "Nord Deep",
    "purple": "#b48ead",
    "red": "#bf616a",
    "white": "#e5e9f0",
    "yellow": "#ebcb8b"
}
```

**Comment by marlosirapuan** [comment]
hello, @richeney! thank you.. yeah, i'm a big fan of Mr. Sly 👊 
Please, can you send me a screen shot with this color set in Windows Terminal? I will put in README. :D

**Comment by richeney** [comment]
![WindowsTerminal_N1d4fU5yFO](https://user-images.githubusercontent.com/24895350/84019838-c20d2600-a979-11ea-998c-6e0574c237a7.png)

**Comment by marlosirapuan** [comment]
Done. Thank you, @richeney
